package com.demo.dynamicjsonui.dynamicui.constants

object JsonFormConstants {

    const val FIRST_STEP_NAME = "step1"
    const val EDIT_TEXT = "text"
    const val EMAIL_TEXT = "email"
    const val PASSWORD_TEXT = "password"
    const val NUMBER_TEXT = "numeric"
    const val DATE_TEXT = "date"
    const val CHECK_BOX = "multi_checkboxtext"
    const val RADIO_BUTTON = "multi_radio"
    const val LABEL = "label"
    const val CHOOSE_IMAGE = "choose_image"
    const val OPTIONS_FIELD_NAME = "options"
    const val OPTIONS_FIELD_CHECK = "field"
    const val SPINNER = "select"
    const val VIDEO_VIEW = "video_view"
    const val SIGN_VIEW = "signature"
    const val TEXT_AREA = "textarea"
    const val MULTI_CHECKBOX = "checkbox"
    const val MULTI_RADIO = "radio"
    const val BARCODE_VIEW = "barcode"
    const val CUSTOM_IMAGE_VIEW = "image"
    const val CUSTOM_CARD_VIEW = "card"
    const val CUSTOM_BUTTON_VIEW = "button"
    const val CUSTOM_LINEAR_VIEW = "linear"
    const val RECORD_AUDIO_VIEW = "recordAudio"
    const val RECORD_VIDEO_VIEW = "recordVideo"
    const val UPLOAD_AUDIO_VIEW = "uploadAudio"
    const val UPLOAD_VIDEO_VIEW = "uploadVideo"
    const val GPS_VIEW = "gps"
    const val MULTI_SPINNER = "multi_select"
    const val LIST_VIEW = "list"
}